source_stream_name = "stg-trans-event"
output_stream_name = "stg-trans-event-prediction"
ecr_repo_name = "credit-card-fraud-detection"
aws_region = "us-east-2"
project_id = "credit-card-fraud-detection"
